AWSTemplateFormatVersion: '2010-09-09'
Description: Configuração Mínima EC2 + RDS

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: fatec-5sem

  SSHLocation:
    Type: String
    Default: 0.0.0.0/0

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmazonLinuxAMI
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref SubnetId
          GroupSet: [!Ref EC2SecurityGroup]
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum install postgresql15 -y

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !GetAtt EC2SecurityGroup.GroupId

  PostgreSQLRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      DBInstanceClass: db.t2.micro
      MasterUsername: admin
      MasterUserPassword: SenhaTemp123
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups: [!GetAtt RDSSecurityGroup.GroupId]

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      SubnetIds: [!Ref SubnetId, !Ref SubnetId]

  LatestAmazonLinuxAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64

  VpcId:
    Type: AWS::EC2::VPC::Id

  SubnetId:
    Type: AWS::EC2::Subnet::Id

Outputs:
  EC2IP:
    Value: !GetAtt EC2Instance.PublicIp
  RDSAddress:
    Value: !GetAtt PostgreSQLRDS.Endpoint.Address