AWSTemplateFormatVersion: '2010-09-09'
Description: Configuração EC2 + RDS com Importação de Recursos Existentes

Parameters:
  # Parâmetros para recursos EXISTENTES (a serem importados)
  ExistingVPC:
    Type: AWS::EC2::VPC::Id
    Description: ID da VPC existente

  ExistingPublicSubnet:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet pública existente para EC2

  ExistingPrivateSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Lista de subnets privadas existentes para RDS

  ExistingKeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Nome da chave SSH existente

  # Parâmetros para configurações dinâmicas
  SSHLocation:
    Description: IP para acesso SSH (formato CIDR)
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: ^(\d{1,3}\.){3}\d{1,3}/\d{1,2}$

  DBUser:
    Description: Usuário do banco de dados
    Type: String
    Default: admin

  DBPassword:
    Description: Senha do banco (mínimo 8 caracteres)
    Type: String
    NoEcho: true
    MinLength: 8

Resources:
  # Security Groups (novos recursos)
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DeletionPolicy: Delete
    Properties:
      GroupDescription: Acesso SSH restrito
      VpcId: !Ref ExistingVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DeletionPolicy: Delete
    Properties:
      GroupDescription: Acesso PostgreSQL da EC2
      VpcId: !Ref ExistingVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !GetAtt EC2SecurityGroup.GroupId

  # EC2 Instance (novo recurso)
  EC2Instance:
    Type: AWS::EC2::Instance
    DeletionPolicy: Delete
    Properties:
      ImageId: !Ref ExistingAmazonLinuxAMI
      InstanceType: t2.micro
      KeyName: !Ref ExistingKeyPair
      SubnetId: !Ref ExistingPublicSubnet
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update -y
          sudo amazon-linux-extras install postgresql15 -y

  # RDS (novo recurso)
  PostgreSQLRDS:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      Engine: postgres
      EngineVersion: 15
      DBInstanceClass: db.t4g.micro
      AllocatedStorage: 20
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VPCSecurityGroups:
        - !GetAtt RDSSecurityGroup.GroupId

  # DB Subnet Group (usa subnets existentes)
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    DeletionPolicy: Delete
    Properties:
      DBSubnetGroupDescription: Subnet Group para RDS
      SubnetIds: !Ref ExistingPrivateSubnets