name: Verificar arquivo do aluno
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  verificar-arquivo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Verificar terceira linha (Windows compatível)
        run: |
          if (Select-String -Path "index.html" -Pattern "terceira linha") {
            Write-Output "✅ Terceira linha encontrada!"
          } else {
            Write-Output "❌ Terceira linha NÃO encontrada!"
            exit 1
          }